name: check

on:
  pull_request:

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install Hatch
        uses: pypa/hatch@install
      - run: hatch fmt

  types:
    name: types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Install Hatch
        uses: pypa/hatch@install
      - run: hatch run types:check
