name: check

on:
  pull_request:

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Enable caching
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Setup Hatch
        uses: pypa/hatch@install
      - name: Run Format
        run: hatch fmt

  types:
    name: types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Enable caching
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Setup Hatch
        uses: pypa/hatch@install
      - name: Run Type Check
        run: hatch run types:check
